export const case1 = [
  {
    id: 1,
    isSelected: false,
    horizontalGap: 20,
    width: 100,
    height: 210,
    gridCardRef: [],
    components: [],
    containerLineType: 1,
    containerLineStyle: {
      display: "grid",
      justifyContent: "center",
    },
    cardStyle: {
      display: "flex",
      justifyContent: "center",
      width: "720px",
      height: "150px",
    },
  },
  {
    id: 2,
    isSelected: false,
    horizontalGap: 20,
    width: 100,
    height: 210,
    gridCardRef: [],
    components: [],
    containerLineType: 1,
    containerLineStyle: {
      display: "grid",
      justifyContent: "center",
    },
    cardStyle: {
      display: "flex",
      justifyContent: "center",
      width: "720px",
      height: "150px",
    },
  },
];

export const case2 = [
  {
    id: 1,
    isSelected: false,
    horizontalGap: 20,
    width: 100,
    height: 210,
    gridCardRef: [],
    components: [],
    containerLineType: 1,
    containerLineStyle: {
      display: "grid",
      justifyContent: "center",
    },
    cardStyle: {
      display: "flex",
      justifyContent: "center",
      width: "683x",
      height: "127px",
    },
  },
  {
    id: 2,
    isSelected: false,
    horizontalGap: 20,
    width: 100,
    height: 210,
    gridCardRef: [],
    components: [],
    containerLineType: 1,
    containerLineStyle: {
      display: "grid",
      justifyContent: "center",
    },
    cardStyle: {
      display: "flex",
      justifyContent: "center",
      width: "683px",
      height: "127px",
    },
  },
];

export const case3 = [
  {
    id: 1,
    isSelected: false,
    horizontalGap: 20,
    width: 100,
    height: 210,
    gridCardRef: [],
    components: [],
    containerLineType: 1,
    containerLineStyle: {
      display: "flex",
      justifyContent: "center",
    },
    cardStyle: {
      display: "flex",
      justifyContent: "center",
      width: "150px",
      height: "350px",
    },
  },
  {
    id: 2,
    isSelected: false,
    horizontalGap: 20,
    width: 100,
    height: 210,
    gridCardRef: [],
    components: [],
    containerLineType: 1,
    containerLineStyle: {
      display: "grid",
      justifyContent: "center",
    },
    cardStyle: {
      display: "flex",
      justifyContent: "center",
      width: "150px",
      height: "350px",
    },
  },
  {
    id: 3,
    isSelected: false,
    horizontalGap: 20,
    width: 100,
    height: 210,
    gridCardRef: [],
    components: [],
    containerLineType: 1,
    containerLineStyle: {
      display: "grid",
      justifyContent: "center",
    },
    cardStyle: {
      display: "flex",
      justifyContent: "center",
      width: "150px",
      height: "350px",
    },
  },
];

export const case4 = [
  {
    id: 1,
    isSelected: false,
    horizontalGap: 10,
    width: 100,
    height: 210,
    gridCardRef: [],
    components: [],
    containerLineType: 1,
    containerLineStyle: {
      display: "flex",
      justifyContent: "center",
    },
    cardStyle: {
      display: "flex",
      justifyContent: "center",
      width: "150px",
      height: "350px",
    },
  },
  {
    id: 2,
    isSelected: false,
    horizontalGap: 10,
    width: 100,
    height: 210,
    gridCardRef: [],
    components: [],
    containerLineType: 1,
    containerLineStyle: {
      display: "grid",
      justifyContent: "center",
    },
    cardStyle: {
      display: "flex",
      justifyContent: "center",
      width: "150px",
      height: "350px",
    },
  },
  {
    id: 3,
    isSelected: false,
    horizontalGap: 10,
    width: 100,
    height: 210,
    gridCardRef: [],
    components: [],
    containerLineType: 1,
    containerLineStyle: {
      display: "grid",
      justifyContent: "center",
    },
    cardStyle: {
      display: "flex",
      justifyContent: "center",
      width: "150px",
      height: "350px",
    },
  },
];

export const case5 = [
  {
    id: 1,
    isSelected: false,
    horizontalGap: 10,
    width: 100,
    height: 210,
    gridCardRef: [],
    components: [],
    containerLineType: 1,
    containerLineStyle: {
      display: "flex",
      justifyContent: "center",
    },
    cardStyle: {
      display: "flex",
      justifyContent: "center",
      width: "100px",
      height: "350px",
    },
  },
  {
    id: 2,
    isSelected: false,
    horizontalGap: 10,
    width: 100,
    height: 210,
    gridCardRef: [],
    components: [],
    containerLineType: 1,
    containerLineStyle: {
      display: "grid",
      justifyContent: "center",
    },
    cardStyle: {
      display: "flex",
      justifyContent: "center",
      width: "420px",
      height: "350px",
    },
  },
  {
    id: 3,
    isSelected: false,
    horizontalGap: 10,
    width: 100,
    height: 210,
    gridCardRef: [],
    components: [],
    containerLineType: 1,
    containerLineStyle: {
      display: "grid",
      justifyContent: "center",
    },
    cardStyle: {
      display: "flex",
      justifyContent: "center",
      width: "100px",
      height: "350px",
    },
  },
];

export const case6 = [
  [
    {
      id: 1,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "150px",
        height: "150px",
      },
    },
    {
      id: 2,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "300px",
        height: "150px",
      },
    },
  ],
  [
    {
      id: 3,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "150px",
        height: "150px",
      },
    },
    {
      id: 4,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "300px",
        height: "150px",
      },
    },
  ],
  [
    {
      id: 5,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "150px",
        height: "150px",
      },
    },
    {
      id: 6,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "300px",
        height: "150px",
      },
    },
  ],
];

export const case7 = [
  [
    {
      id: 1,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "150px",
        height: "150px",
      },
    },
    {
      id: 2,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "150px",
        height: "150px",
      },
    },
    {
      id: 3,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "150px",
        height: "150px",
      },
    },
  ],
  [
    {
      id: 4,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "150px",
        height: "150px",
      },
    },
    {
      id: 5,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "150px",
        height: "150px",
      },
    },
    {
      id: 6,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "150px",
        height: "150px",
      },
    },
  ],
  [
    {
      id: 7,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "150px",
        height: "150px",
      },
    },
    {
      id: 8,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "150px",
        height: "150px",
      },
    },
    {
      id: 9,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "150px",
        height: "150px",
      },
    },
  ],
];

export const case8 = [
  [
    {
      id: 1,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "220px",
        height: "380px",
      },
    },
  ],
  [
    {
      id: 2,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "310px",
        height: "150px",
      },
    },
    {
      id: 3,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "150px",
        height: "150px",
      },
    },
    {
      id: 4,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "150px",
        height: "150px",
      },
    },
  ],
];

export const case9 = [
  [
    {
      id: 1,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "780px",
        height: "143px",
      },
    },
  ],
  [
    {
      id: 2,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "780px",
        height: "143px",
      },
    },
  ],
  [
    {
      id: 3,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "780px",
        height: "143px",
      },
    },
  ],
  [
    {
      id: 4,
      isSelected: false,
      horizontalGap: 10,
      width: 100,
      height: 210,
      gridCardRef: [],
      components: [],
      containerLineType: 1,
      containerLineStyle: {
        display: "flex",
        justifyContent: "center",
      },
      cardStyle: {
        display: "flex",
        justifyContent: "center",
        width: "780px",
        height: "143px",
      },
    },
  ],
];

export default case1;
